### ISSUE TITLE
Templates/Loop exercise causes to crash the k8s node

### ISSUE THREAD

**Issue by sinorch** [argoproj-labs/training-material#79]
Exercise
Change the withSequence to print the numbers 10 to 20.

When the exercise is done by setting such config:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: with-sequence-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: print-message
            template: echo
            arguments:
              parameters:
                - name: message
                  value: "{{item}}"
            withSequence:
              start: 10
              end: 20

    - name: echo
      inputs:
        parameters:
          - name: message
      container:
        image: busybox
        command: [echo]
        args: ["{{inputs.parameters.message}}"]
```
the cluster fails 2 minutes after workflow starts, k8s api become non-responsive. In case sequence kept in low numbers (Ex: 10-13) then WF completes successfully.
